// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameURL = "urls"

// URL mapped from table <urls>
type URL struct {
	ID          int64                 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64                 `gorm:"column:user_id;type:int;not null" json:"user_id"`
	OriginalURL string                `gorm:"column:original_url;type:text;not null" json:"original_url"`
	ShortCode   string                `gorm:"column:short_code;type:varchar(255);not null" json:"short_code"`
	IsCustom    int64                 `gorm:"column:is_custom;type:tinyint(1);not null" json:"is_custom"`
	Views       int64                 `gorm:"column:views;type:int;not null" json:"views"`
	ExpiredAt   int64                 `gorm:"column:expired_at;type:bigint;not null" json:"expired_at"`
	CreatedAt   int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt   int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint;softDelete:unix" json:"-"`
}

// TableName URL's table name
func (*URL) TableName() string {
	return TableNameURL
}
