// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64                 `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Email        string                `gorm:"column:email;type:varchar(255);not null" json:"email"`
	PasswordHash string                `gorm:"column:password_hash;type:text;not null" json:"password_hash"`
	CreatedAt    int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt    int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt    soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint;softDelete:unix" json:"-"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
