[system]
port = ":7788"
host = "127.0.0.1"

[mysql]
source = "root:password@tcp(127.0.0.1:3306)/urlshortener?charset=utf8mb4&parseTime=True&loc=Local"

[redis]
addr = "127.0.0.1:6379"
username = ""
password = ""
db = 0
use_cluster = false
cluster_addrs = [""]

[zap_log]
log_level = "debug"
encoding = "console"  # json or console
log_file_name = "./storage/logs/server.log"
max_backups = 30
max_age = 7
max_size = 1024
compress = true
