// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/xxfasu/urlshortener/internal/middleware"
	"github.com/xxfasu/urlshortener/routes"
)

// Injectors from wire.go:

func NewWire() (*gin.Engine, func(), error) {
	recovery := middleware.NewRecoveryM()
	cors := middleware.NewCorsM()
	logM := middleware.NewLogM()
	engine := routes.NewRouter(recovery, cors, logM)
	return engine, func() {
	}, nil
}
